---

name: Devel

on:
  push:
    branches: [devel]

jobs:
  release:
    runs-on: ubuntu-18.04
    name: Push devel image
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          IMG=awx-operator:devel make docker-build

      - name: Push To GCR
        uses: RaccoonDev/push-docker-gcr@v1
        with:
          image_name: awx-operator
          image_tag: devel
          gcr_host: eu.gcr.io/vaz-dev4e2f30b1/
