---
name: Promote AWX Operator image
on:
  release:
    types: [published]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release Helm chart
        run: |
          ansible-playbook ansible/helm-release.yml -v \
            -e operator_image=quay.io/${{ github.repository }} \
            -e chart_owner=${{ github.repository_owner }} \
            -e tag=${{ github.event.release.tag_name }} \
            -e gh_token=${{ secrets.GITHUB_TOKEN }}
